// <auto-generated />
using System;
using Crypto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crypto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crypto.Entities.Carteira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SaldoBrl")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Carteiras");
                });

            modelBuilder.Entity("Crypto.Entities.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Simbolo")
                        .IsUnique();

                    b.ToTable("Moedas");
                });

            modelBuilder.Entity("Crypto.Entities.SaldoCripto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CarteiraId")
                        .HasColumnType("integer");

                    b.Property<int?>("CarteiraId1")
                        .HasColumnType("integer");

                    b.Property<int>("MoedaId")
                        .HasColumnType("integer");

                    b.Property<int?>("MoedaId1")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CarteiraId");

                    b.HasIndex("CarteiraId1")
                        .IsUnique();

                    b.HasIndex("MoedaId")
                        .IsUnique();

                    b.HasIndex("MoedaId1")
                        .IsUnique();

                    b.ToTable("SaldoCriptos");
                });

            modelBuilder.Entity("Crypto.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Crypto.Entities.Carteira", b =>
                {
                    b.HasOne("Crypto.Entities.Usuario", "Usuario")
                        .WithOne("Carteira")
                        .HasForeignKey("Crypto.Entities.Carteira", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Crypto.Entities.SaldoCripto", b =>
                {
                    b.HasOne("Crypto.Entities.Carteira", "Carteira")
                        .WithMany("Saldos")
                        .HasForeignKey("CarteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crypto.Entities.Carteira", null)
                        .WithOne("SaldoCripto")
                        .HasForeignKey("Crypto.Entities.SaldoCripto", "CarteiraId1");

                    b.HasOne("Crypto.Entities.Moeda", "Moeda")
                        .WithOne()
                        .HasForeignKey("Crypto.Entities.SaldoCripto", "MoedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crypto.Entities.Moeda", null)
                        .WithOne("SaldoCripto")
                        .HasForeignKey("Crypto.Entities.SaldoCripto", "MoedaId1");

                    b.Navigation("Carteira");

                    b.Navigation("Moeda");
                });

            modelBuilder.Entity("Crypto.Entities.Carteira", b =>
                {
                    b.Navigation("SaldoCripto");

                    b.Navigation("Saldos");
                });

            modelBuilder.Entity("Crypto.Entities.Moeda", b =>
                {
                    b.Navigation("SaldoCripto");
                });

            modelBuilder.Entity("Crypto.Entities.Usuario", b =>
                {
                    b.Navigation("Carteira");
                });
#pragma warning restore 612, 618
        }
    }
}
